version: '3'

services:
  flask:
    restart: always
    build: ./flask
    expose:
      - "8000"
    volumes:
      - web-data:/usr/src/app/static
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - .:/www/static
      - web-data:/usr/src/app/static
    links:
      - flask:flask

volumes:
  web-data: